# Generated by Django 2.2.10 on 2020-10-17 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_ref_no', models.CharField(max_length=100, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('employee_id', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=100)),
                ('date_of_join', models.DateField(blank=True, null=True)),
                ('marital_status', models.BooleanField(default=False)),
                ('physical_disabled', models.BooleanField(default=False)),
                ('chronic_illness', models.CharField(default=0, max_length=100)),
                ('gender', models.CharField(max_length=6)),
                ('status', models.CharField(default='Pending', max_length=25)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
