# Generated by Django 2.2.10 on 2020-10-17 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_auto_20201017_1424'),
        ('applications', '0002_auto_20201017_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='TransferAllotment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='application', to='applications.Application')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='school', to='masters.School')),
            ],
        ),
    ]
