# Generated by Django 2.2.10 on 2020-10-17 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_auto_20201017_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
