# Generated by Django 2.2.10 on 2020-10-18 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_application_is_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='years_of_exp',
            field=models.IntegerField(default=0),
        ),
    ]
