# Generated by Django 2.2.10 on 2020-10-18 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_auto_20201017_1424'),
        ('applications', '0005_application_years_of_exp'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='current_school', to='masters.School'),
        ),
    ]
