# Generated by Django 2.2.10 on 2020-10-18 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_auto_20201017_1424'),
        ('applications', '0006_application_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefernce_no', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='employee', to='applications.Application')),
                ('prefer_school', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='prefer_school', to='masters.School')),
            ],
        ),
    ]
