# Generated by Django 2.2.10 on 2020-10-18 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_emppreferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
