# Generated by Django 2.2.10 on 2020-10-18 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_application_date_of_birth'),
        ('masters', '0002_auto_20201017_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='designation', to='masters.Designation')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='alloted_emp', to='applications.Application')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='vacancy_school', to='masters.School')),
            ],
        ),
    ]
